import turtle
import random
t=turtle.Pen()
t.speed(0)
ts=turtle.Pen()
ts.speed(0)
t.pensize(2)
turtle.colormode(255)
t.hideturtle()
ts.hideturtle()
turtle.bgcolor('black')
for i in range(0, 72):
    r=random.randint(0,255)
    g=random.randint(0,255)
    b=random.randint(0,255)
    t.color(r,g,b)
    t.circle(150)
    t.lt(5)
    r=random.randint(0,255)
    g=random.randint(0,255)
    b=random.randint(0,255)
    ts.color(r,g,b)
    ts.circle(100)
    ts.rt(5)
turtle.exitonclick()
